export const product_images: any = {
    bearing: require("../../../img/products_img/bearing.jpg"),
    bike_chamber: require("../../../img/products_img/bike_chamber.jpg"),
    brakes: require("../../../img/products_img/brakes.jpg"),
    brakes2: require("../../../img/products_img/brakes2.jpg"),
    brakes_disk: require("../../../img/products_img/brakes_disk.jpg"),
    caret: require("../../../img/products_img/caret.jpg"),
    chain: require("../../../img/products_img/chain.jpg"),
    fenders: require("../../../img/products_img/fenders.jpg"),
    grips: require("../../../img/products_img/grips.jpg"),
    kasset: require("../../../img/products_img/kasset.jpg"),
    pedals: require("../../../img/products_img/pedals.jpg"),
    rear_switch: require("../../../img/products_img/rear_switch.jpg"),
    shift_cable: require("../../../img/products_img/shift_cable.jpg"),
    shifter: require("../../../img/products_img/shifter.jpg"),
    st_wheel: require("../../../img/products_img/st_wheel.jpg"),
    support_side_wheels: require("../../../img/products_img/support_side_wheels.jpg"),
    tire: require("../../../img/products_img/tire.jpg"),
};